ktor {
  deployment {
    port = 8080
    host = "0.0.0.0"
  }

  application {
    modules = [ com.example.ApplicationKt.module ]
  }
}

database {
  url = "jdbc:postgresql://dpg-d5j6seffte5s73d77lv0-a.virginia-postgres.render.com:5432/astrodb_butz"
  user = "admin"
  password = "58ytBawJvrha1R6GQxTtgb6crn60Tlfl"
}

jwt {
    secret = "secret"
    issuer = "http://0.0.0.0:8080/"
    audience = "http://0.0.0.0:8080/hello"
    realm = "Access to 'hello'"
}